content:
  git:
    repo: https://github.com/life-and-dev/kingdom
siteName: 'The Kingdom of God'
themes:
  light:
    colors:
      primary: '#208060'
      secondary: '#ffffff'
      selected: '#208060'
      error: '#d64d5b'
      warning: '#c29e4a'
      info: '#548af7'
      success: '#6aab73'
      background: '#f5f9f9'
      surface: '#ffffff'
      surface-rail: '#edf5f5'
      surface-appbar: '#e4f0f0'
      on-surface-rail: '#2a3030'
      on-surface-appbar: '#000000'
      on-background: '#242929'
      on-surface: '#242929'
      on-primary: '#ffffff'
      on-secondary: '#ffffff'
      on-selectable: '#242929'
      on-selected: '#ffffff'
      on-error: '#ffffff'
      on-warning: '#ffffff'
      on-info: '#ffffff'
      on-success: '#ffffff'
      outline: '#d0d7d7'
      outline-bars: '#f3f4f4'
  dark:
    colors:
      primary: '#5faf8f'
      secondary: '#2d302b'
      selected: '#5faf8f'
      error: '#d64d5b'
      warning: '#c29e4a'
      info: '#548af7'
      success: '#6aab73'
      background: '#161b1b'
      surface: '#0d1111'
      surface-rail: '#1f2525'
      surface-appbar: '#282f2f'
      on-surface-rail: '#ced0d0'
      on-surface-appbar: '#ffffff'
      on-background: '#d1c9c9'
      on-surface: '#d1c9c9'
      on-primary: '#110d0d'
      on-secondary: '#110d0d'
      on-selectable: '#d1c9c9'
      on-selected: '#ffffff'
      on-error: '#ffffff'
      on-warning: '#ffffff'
      on-info: '#ffffff'
      on-success: '#ffffff'
      outline: '#363030'
      outline-bars: '#1b1616'
